#!/bin/bash

compile="compile";
clean="clean";
zip="zip"

if test -z "$2"
then
    if [ $1 = $clean ]; 
    then
        echo "Cleaning please wait ..."
        rm -f *~
        rm -rf *.aux
        rm -rf *.bbl
        rm -rf *.blg
        rm -rf *.d
        rm -rf *.fls
        rm -rf *.ilg
        rm -rf *.ind
        rm -rf *.toc*
        rm -rf *.lot*
        rm -rf *.lof*
        rm -rf *.log
        rm -rf *.idx
        rm -rf *.out*
        rm -rf *.nlo
        rm -rf *.nls
        rm -rf $filename.pdf
        rm -rf $filename.ps
        rm -rf $filename.dvi
        rm -rf *#*
        echo "Cleaning complete!"
        exit
    else
        echo "Shell script for compiling your latex file"
        echo "Usage: sh ./compile.sh [OPTIONS] [filename]"
        echo "[option]  compile: Compiles your latex file"
        echo "[option]  clean: removes temporary files no filename required"
        exit
    fi
fi

fullfilename=$2;
filename="${fullfilename%.*}";

if [ $1 = $clean ]; then
    echo "Cleaning please wait ..."
    rm -f *~
    rm -rf *.aux
    rm -rf *.bbl
    rm -rf *.blg
    rm -rf *.d
    rm -rf *.fls
    rm -rf *.ilg
    rm -rf *.ind
    rm -rf *.toc*
    rm -rf *.lot*
    rm -rf *.lof*
    rm -rf *.log
    rm -rf *.idx
    rm -rf *.out*
    rm -rf *.nlo
    rm -rf *.nls
    rm -rf *.cut
    rm -rf *.hd
    rm -rf *.rpi
    rm -rf *.tgz
    rm -rf *.thm
    rm -rf $filename.pdf
    rm -rf $filename.ps
    rm -rf $filename.dvi
    rm -rf *#*
    echo "Cleaning complete!"
    exit
elif [ $1 = $compile ]; then
    echo "Compiling your latex file using pdflatex command...please wait...!"
    ##############old-command##########################################
    echo "-------------------------------------------------------------------"
    echo "pdflatex..."
    pdflatex -synctex=1 -interaction=nonstopmode $filename.tex
    echo "-------------------------------------------------------------------"
    echo "bibtex..."
    bibtex $filename.aux
    echo "-------------------------------------------------------------------"
    echo "makeindex..."
    makeindex $filename.aux
    makeindex $filename.idx
    makeindex $filename.nlo -s nomencl.ist -o $filename.nls
    echo "-------------------------------------------------------------------"
    echo "pdflatex again..."
    pdflatex -synctex=1 -interaction=nonstopmode $filename.tex
    makeindex $filename.nlo -s nomencl.ist -o $filename.nls
    echo "-------------------------------------------------------------------"
    echo "pdflatex again again..."
    pdflatex -synctex=1 -interaction=nonstopmode $filename.tex
    #############end##################################################
    echo "-------------------------------------------------------------------"
    echo "Success!"
    echo "End here!"
    exit
elif [ $1 = $zip ]; then
    echo "Compress all your latex files...please wait...!"
    zip -r  ${filename}.zip * -x '*~' -x '*.tgz' -x '*.zip' -x CVS -x 'CVS/*'
    echo "Success!"
    exit
fi

if test -z "$3"
then
    exit
fi
