#!/usr/bin/env bash
#vim:ts=2:sw=2:expandtab
echo "Installing prerequisites for pacaur..."
sudo pacman --noconfirm -S git git-core

echo "Installing pacaur..."
if ! command -v "pacaur" >/dev/null 2>&1; then
    mkdir /tmp/tmp-pacaur
    cd /tmp/tmp-pacaur
    wget https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur -O PKGBUILD
    makepkg
    sudo pacman --noconfirm -U *.tar.xz
    cd -
fi

echo "Installing base packages..."
sudo pacman --noconfirm -S \
  termite-git \
  bash-completion

echo "Installing tools..."
sudo pacman --noconfirm -S \
  mplayer \
  evince \
  mupdf \
  mupdf-tools \
  gvim \
  texmacs \
  anydesk \
  megasync \
  gimp \
  inkscape \
  shutter \
  xclip \
  synaptics \
  emacs \
  firefox \
  htop \
  eog \
  tmux \
  shadowsocks-qt5 \
  google-chrome \
  imagemagick




