#!/usr/bin/env bash
#vim:ts=2:sw=2:expandtab

echo "Installing prerequisites for pacaur..."
sudo pacman -S base-devel fakeroot jshon expac cower wget
echo "Installing pacaur..."
if ! command -v "pacaur" >/dev/null 2>&1; then
mkdir /tmp/tmp-pacaur
cd /tmp/tmp-pacaur
wget https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur -O PKGBUILD
makepkg
sudo pacman --noconfirm -U *.tar.xz
cd -
fi

echo "Install sogou Chinese input method..."
sudo pacman --noconfirm -S \
     fcitx-im \
     fcitx-configtool \
     fcitx-sogoupinyin

#{{{ softwares I often used
echo "Installing my tools..."
pacaur --noconfirm --noedit -S \
     unrar \
     unzip \
     mplayer \
     smplayer \
     evince \
     mupdf \
     mupdf-tools \
     zathura \
     okular \
     vim \
     texmacs \
     anydesk \
     megasync \
     gimp \
     inkscape \
     shutter \
     xclip \
     synaptics \
     emacs-git \
     firefox \
     htop \
     eog \
     tmux \
     xdotool \
     wmctrl \
     shadowsocks-qt5 \
     google-chrome \
     imagemagick \
     percol \
     electronic-wechat \
     youtube-dl \
     gnuplot \
     rofi \
##}}}

##{{{ other useful stuffs
sudo pacman --noconfirm -S \
     libqalculate \
     xf86-input-synaptics \
     ttf-font-icons \
     ruby \
     aspell-en \
     xorg \
     gbkunzip \
     xsel \
     libqalculate # rofi dependency
##}}}

##{{{ install python scientific computing environment
echo "Installing python scientific computing environment "
pacaur --noconfirm --noedit -S \
     python2-pip \
     python-pip
echo "Installing python scientific computing environment: python2"
sudo pip2 install \
     numpy \
     scipy \
     Cython \
     matplotlib \
     scikit-image \
     pillow \
     scikit-learn
echo "Installing python scientific computing environment: python3"
sudo pip3 install \
     numpy \
     scipy \
     Cython \
     matplotlib \
     scikit-image \
     pillow \
     scikit-learn
##}}}

echo "Installing other libaray"
yaourt --noconfirm -S \
     ann \
     boost \
     tk # for python
# }}

# {{
echo "Installing java"
yaourt --noconfirm -S \
     jdk # need you input password
# }}

echo "Installing auctex..."
cd ~
wget -c http://ftp.gnu.org/pub/gnu/auctex/auctex-12.1.tar.gz
tar -xzvf auctex-12.1.tar.gz
cd auctex-12.1
#./configure --prefix=$HOME/.emacs.d/site-lisp/auctex --with-lispdir=$HOME/.emacs.d/site-lisp/auctex --with-texmf-dir=$HOME/.local/lib/texmf &&
./configure
make &&
    sudo make install
cd ~ && rm -rf ./auctex-12.1 && rm -rf ./auctex-12.1.tar.gz
